# Generated by Django 3.2.4 on 2021-07-19 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='webapps',
            new_name='webapp',
        ),
    ]
